### ISSUE TITLE
Add a "tombstone" page for withdrawn versions

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/purl#1042]
If a user is trying to display a withdrawn version display a "tombstone" page indicating they are attempting to view a withdrawn version.

**Comment by andrewjbtw** [comment]
Adding some clarifying notes in response to questions on Slack:

- If there is only one user version:
  - We still need to tombstone it if it has a DOI (DataCite/DOI requirement)
  - We do not tombstone it otherwise, we make the item dark by changing the access rights (as per current takedown practice)

**Comment by astridu** [comment]
Mock up: https://www.figma.com/proto/XjubCohES3rE8xSQpiNghq/Versioning?page-id=0%3A1&node-id=276-340&viewport=-12727%2C-3675%2C1&t=Q8XjDGjx2EhhCXEa-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=276%3A340

We are using the yellow info alert (the alert styles were defined during the last Preassembly workcycle, not sure if you can reference them so you don't have to build them all over again). Here are the specs:

1. Stroke=F6C64A
2. Background=FEF9EA
3. Exclamation icon=FEC51D
4. Text in bold: This version has been withdrawn
5. Regular text: Please visit [https://purl.stanford.edu/cd366rw7886](https://purl.stanford.edu/cd366rw7886) to view the other versions of this item. [PURL should be hyperlinked]
