### ISSUE TITLE
Add authentication service description for location-based restrictions

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/purl#134]
(Presumably based on http://iiif.io/api/auth/1.0/#external-interaction-pattern?)

We've made this change in stacks, but it would be a courtesy to consuming clients to also expose this information in our presentation manifests.

**Comment by cbeer** [comment]
@blalbrit to provide example image objects.

**Comment by blalbrit** [comment]
Checking with spec to see if the Buckminster Fuller collection is a candidate for location restriction. No content currently in prod since this was not an available feature to-date.

A list of location-restricted media objects (with images) is available here: https://docs.google.com/spreadsheets/d/1ud5kM_wNLAsRQCdkfqFtzZAwqRHHjE-dwTFh-QNw-sM/edit?usp=sharing

There are also a handful of file objects in that list above.
