### ISSUE TITLE
Support AnnotationLists 

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/purl#452]
Access team is working with @andrewjbtw on a small experiment with From the Page annotations. Let's plan to work on this when we return from break.

script in progress:
https://gist.github.com/camillevilla/4d19805f564092ffc64a7653893d47d5

**Comment by mejackreed** [comment]
I've forked the version of Camille and fixed up to work with the updates in #460.

https://gist.github.com/mejackreed/7546c2947d94ffce5fa3d1c38fbde6d7

@andrewjbtw can you take a look to see if this works for you?

```sh
$ ruby ftp_annotation_harvest.rb
```

**Comment by andrewjbtw** [comment]
@mejackreed this worked for me on my local machine. I got 150 JSON files - I assume that's the correct count? Some images don't have manifests but I'm guessing those are ones that weren't transcribed (blank covers, etc.).

**Comment by mejackreed** [comment]
@andrewjbtw that's great! The From The Page people also suggest ingesting the transcription in a text file which we could do. I'm not sure if this is something we would like to scope in/out of this project but I could make an update to the script to do that if we wanted to.

**Comment by andrewjbtw** [comment]
Would that be a single text file per page or for the whole document? I think transcriptions are still in scope, especially if someone would like to download the text.

**Comment by mejackreed** [comment]
It would be a single text file per page. Something like this: https://fromthepage.com/iiif/37594/export/1264411/plaintext/searchable

**Comment by andrewjbtw** [comment]
Let's download that too. From the accessioning side, the impact of adding those text files will be minimal.

**Comment by mejackreed** [comment]
@andrewjbtw sorry for the long delay. I've updated the script (https://gist.github.com/mejackreed/7546c2947d94ffce5fa3d1c38fbde6d7) to support downloading of a text file.

**Comment by andrewjbtw** [comment]
Thanks! I'm working on putting examples in argo-stage.

**Comment by andrewjbtw** [comment]
@mejackreed I have an object on stage with both the file roles set for "annotations" on the JSON files and "transcription" on the text files: https://sul-purl-stage.stanford.edu/bg310zs1069 I am seeing an error with content search but the Purl XML looks correct.

Let me know if that looks correct and I can populate more objects. I loaded the whole Steinbeck set into stage because it's not very large.

**Comment by mejackreed** [comment]
@andrewjbtw thanks so much for doing that. One question about the mimetype there. I would have expected it to be `application/json` can that happen?

**Comment by andrewjbtw** [comment]
I can change that manually after-the-fact but it's coming from an accessioning step and we need to make the change there. I filed an issue for it: https://github.com/sul-dlss/assembly-objectfile/issues/50

**Comment by andrewjbtw** [comment]
@mejackreed I've updated that purl with `application/json` now.

**Comment by mejackreed** [comment]
@andrewjbtw thanks for that! Things seem to be looking correct with the implementation here: https://sul-purl-stage.stanford.edu/bg310zs1069

This requires #460 to be 🚢 (which it is deployed right now in stage). They aren't shi

**Comment by andrewjbtw** [comment]
I've now enabled this on 30 items in stage so there's more variety for review. Since we don't have a way to group purls on the purl pages, I've put them under an Argo tag of "Project annotations" 
https://argo-stage.stanford.edu/catalog?f%5Btag_ssim%5D%5B%5D=Project+%3A+annotations

I can also export a list of all stage purls.
