### ISSUE TITLE
Feedback link causes page refresh

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/purl#78]
Clicking on the feedback link on any page does toggle the feedback form open, however; it also causes the page to reload and the user does not have time to fill out the feedback form.

**Comment by cbeer** [comment]
Some sort of turbolinks 5-related bug? It looks like we are rewriting the link to try to avoid that: https://github.com/sul-dlss/purl/blob/master/app/assets/javascripts/feedback_form.js#L110

(I'm not sure why it does that instead of registering an event handler and preventing the default action? I think I copied it from somewhere else, maybe spotlight or searchworks?)

**Comment by jkeck** [comment]
Yeah, not exactly sure.  I would expect to see `preventDefault()` but that is only on the cancel button.

FWIW, it looks like if the `href` of the feedback link is `javascript:;` instead of `#` things seem to work out okay.

More than happy to submit a PR, was just in the middle of something else when I noticed that.

**Comment by jkeck** [comment]
Of course JSHint says not to do that.  I think the [context](https://stackoverflow.com/questions/2264968/why-is-javascriptvoid0-considered-harmful) that it is considered problematic is irrelevant since we're handling the progressive enhancement case properly (and only changing the `href` when javascript is enabled).

Either way, the change to just use `preventDefault()` seems to be just as minimal and potentially more sane.  I'll do that.
